version: '3.8'

services:
  nest:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
    command: yarn start:dev
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

